
[tool.commitizen]
name = "foo-bar"
version = "0.0.0"
version_files = ["pyproject.toml:version"]
update_changelog_on_bump = true
tag_format = "v$version"
bump_message = ":bookmark: release $current_version -> $new_version [skip ci]"
style = [
    ["qmark", "fg:#ff9d00 bold"],
    ["question", "bold"],
    ["answer", "fg:#ff9d00 bold"],
    ["pointer", "fg:#ff9d00 bold"],
    ["highlighted", "fg:#ff9d00 bold"],
    ["selected", "fg:#cc5454"],
    ["separator", "fg:#cc5454"],
    ["instruction", ""],
    ["text", ""],
    ["disabled", "fg:#858585 italic"],
]
